name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  animated_floating_buttons: ^0.0.2
  bot_toast: ^4.1.3
  icons_launcher: ^3.0.0
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  responsive_framework: ^1.5.1 
  shared_preferences: ^2.3.3
  json_theme_plus: ^6.6.1
  i18n_extension: ^15.0.0
  i18n_extension_importer: ^0.0.6
  go_router: ^15.1.2 
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  reactive_forms: ^17.0.1
  reactive_phone_form_field: ^5.0.1
  reactive_flutter_rating_bar: ^2.0.1
  reactive_dropdown_search: ^5.0.5
  reactive_pinput: ^5.0.0
  flutter_quill: ^11.0.0
  animated_splash_screen: ^1.3.0
  riverpod_annotation: ^2.6.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.20.0
  share_plus: ^11.0.0
  uuid: ^4.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.0+1
  local_hero_transform: ^1.0.6
  local_hero: ^0.3.0
dev_dependencies:
 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/translations/
  #   - assets/
  #   - assets/themes/